---

dashy_services:
- name: dashy
  network:
    name: lanBridge
    ip: 192.168.42.32
    ports:
    - 8080:80
  #resources:
  #  limits:
  #    cpu: 0.500
  #    memory: 1Gi

  # dashy_config is just a representation of the Dashy config file
  # Find more options here: https://github.com/Lissy93/dashy/blob/master/docs/configuring.md
  dashy_config:
    pageInfo:
      title: Kemo Labs
    sections: # An array of sections
    - name: OOBM
      icon: far fa-rocket
      items:
      - title: raza
        description: Core Lab Server
        icon: fab fa-github
        url: https://raza.mgmt.kemo.labs
      - title: foundation
        description: R730 running RHEL
        icon: fab fa-github
        url: https://foundation.mgmt.kemo.labs
      - title: suki
        description: EPYC Server in the living room
        icon: fab fa-github
        url: https://suki.mgmt.kemo.labs
      - title: endurance
        description: EPYC server with bulk compute resources
        icon: fab fa-github
        url: https://endurance.mgmt.kemo.labs
      - title: serenity
        description: R730 that may be borked
        icon: fab fa-github
        url: https://serenity.mgmt.kemo.labs
      - title: rocinante
        description: R720 that runs vSphere
        icon: fab fa-github
        url: https://rocinante.mgmt.kemo.labs

    - name: Cockpit
      icon: far fa-rocket
      items:
      - title: raza
        description: Core Lab Server
        icon: fab fa-github
        url: https://raza.kemo.labs:9090/
      - title: foundation
        description: R730 running RHEL
        icon: fab fa-github
        url: https://foundation.kemo.labs:9090/
      - title: suki
        description: EPYC Server in the living room
        icon: fab fa-github
        url: https://suki.kemo.labs:9090/
      - title: endurance
        description: EPYC server with bulk compute resources
        icon: fab fa-github
        url: https://endurance.kemo.labs:9090/
      - title: serenity
        description: R730 that may be borked
        icon: fab fa-github
        url: https://serenity.kemo.labs:9090/
      - title: IDM
        description: Red Hat Identity Management
        icon: fab fa-github
        url: https://idm.kemo.labs:9090/
      - title: Tower
        description: Red Hat Ansible Tower
        icon: fab fa-github
        url: https://tower.kemo.labs:9090/
      - title: StepCA
        description: StepCA server
        icon: fab fa-github
        url: https://step-ca.kemo.labs:9090/
      - title: Plex
        description: Plex Media Server
        icon: fab fa-github
        url: https://plex.kemo.labs:9090/
      - title: ZeroTier
        description: ZeroTier Network Controller
        icon: fab fa-github
        url: https://zerotier.kemo.labs:9090/
      - title: GitLab
        description: GitLab Server
        icon: fab fa-github
        url: https://gitlab.kemo.labs:9090/

    - name: Identity Services
      items:
      - title: Red Hat Identity Management
        icon: favicon
        url: https://idm.kemo.labs/
      - title: Keycloak SSO
        icon: favicon
        url: https://sso.kemo.labs/
      - title: Step CA
        icon: favicon
        url: https://step-ca.kemo.labs/

    - name: Media Services
      items:
      - title: Sonarr TV
        icon: favicon
        url: https://sonarr.kemo.labs/
      - title: Radarr Movies
        icon: favicon
        url: https://radarr.kemo.labs/
      - title: Bazarr Subtitles
        icon: favicon
        url: https://bazarr.kemo.labs/
      - title: Plex
        icon: favicon
        url: https://plex.kemo.labs/
      - title: Deluge
        icon: favicon
        url: https://deluge-web.kemo.labs/

      - title: Overseerr
        icon: favicon
        url: https://overseerr.kemo.labs/
      - title: Tautilli
        icon: favicon
        url: https://tautulli.kemo.labs/


    - name: Lab Services
      items:
      - title: Kemo Labs Primer
        icon: favicon
        url: https://kemo.labs/
      - title: Metrics Stack (Grafana)
        icon: favicon
        url: https://grafana.kemo.labs/
      - title: Ansible Tower
        icon: favicon
        url: https://tower.kemo.labs/
      - title: GitLab
        icon: favicon
        url: https://gitlab.kemo.labs/
      - title: Core OpenShift Cluster
        icon: favicon
        url: https://console-openshift-console.apps.core-ocp.d70.lab.kemo.network/

    - name: Network Services
      items:
      - title: Unifi UI
        icon: favicon
        url: https://unifi.ui.com/

      - title: Pi-Hole 1
        icon: favicon
        url: https://pihole-1.kemo.labs/admin
      - title: Pi-Hole 2
        icon: favicon
        url: https://pihole-2.kemo.labs/admin

    - name: Container Image Registries
      items:
      - title: Nexus
        icon: favicon
        url: https://nexus.kemo.labs/
      - title: Quay
        icon: favicon
        url: https://quay.kemo.labs/
      - title: Harbor
        icon: favicon
        url: https://harbor.kemo.labs/
      - title: Artifactory
        icon: favicon
        url: https://artifactory.kemo.labs/

    - name: Tools
      items:
      - title: HackMD
        icon: favicon
        url: https://hackmd.com/
      - title: GitHub
        icon: favicon
        url: https://github.com/